services:
  proyectomanhattan.server:
    image: ${DOCKER_REGISTRY-}proyectomanhattanserver
    container_name: proyectomanhattan.server
    build:
      context: .
      dockerfile: ProyectoManhattan.Server/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=yourpass
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
        - ./ProyectoManhattan.Server/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
  
  proyectomanhattan.database:
    image: postgres:15
    container_name: proyectomanhattan.database
    environment:
      - POSTGRES_DB=ProyectoManhattanDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./.containers/proyectomanhattan-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

