services:
  proyectomanhattan.server:
    image: ${DOCKER_REGISTRY-}proyectomanhattanserver
    domainname: proyecto-manhattan.com
    container_name: proyectomanhattan.server
    networks:
      - nginx_network
    build:
      context: .
      dockerfile: ProyectoManhattan.Server/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    #environment:
    #    - Kestrel__Certificates__Default__Path=/root/.aspnet/https/aspnetapp.pfx
    #    - Kestrel__Certificates__Default__Password=changeit
    #volumes:
    #  - ~/root\.aspnet\https:/root/.aspnet/https
  
  proyectomanhattan.database:
    image: postgres:15
    container_name: proyectomanhattan.database
    networks:
      - nginx_network
    environment:
      - POSTGRES_DB=ProyectoManhattanDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./.containers/proyectomanhattan-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
networks:
  nginx_network:
    external: true
