// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProyectoManhattan.Infrastructure.Persistance;

#nullable disable

namespace ProyectoManhattan.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240923043633_AddedReports")]
    partial class AddedReports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Brand", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("SapName")
                        .HasColumnType("text");

                    b.Property<string>("Uneco")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("Domain.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CalculationTime")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Domain.Entities.Shoe", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("BrandSapName")
                        .HasColumnType("text");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Ean")
                        .HasColumnType("text");

                    b.Property<string>("Matnr")
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<int?>("ShoeModelId")
                        .HasColumnType("integer");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShoeModelId");

                    b.ToTable("Shoe");
                });

            modelBuilder.Entity("Domain.Entities.ShoeModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("integer");

                    b.Property<string>("BrandSapName")
                        .HasColumnType("text");

                    b.Property<string>("Family")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("RefWithOutSize")
                        .HasColumnType("text");

                    b.Property<int?>("ReportId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReportId1")
                        .HasColumnType("integer");

                    b.Property<int?>("ReportId2")
                        .HasColumnType("integer");

                    b.Property<int?>("ReportId3")
                        .HasColumnType("integer");

                    b.Property<int?>("ReportId4")
                        .HasColumnType("integer");

                    b.Property<string>("Uneco")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ReportId");

                    b.HasIndex("ReportId1");

                    b.HasIndex("ReportId2");

                    b.HasIndex("ReportId3");

                    b.HasIndex("ReportId4");

                    b.ToTable("ShoeModel");
                });

            modelBuilder.Entity("Domain.Entities.Shoe", b =>
                {
                    b.HasOne("Domain.Entities.ShoeModel", null)
                        .WithMany("Sizes")
                        .HasForeignKey("ShoeModelId");
                });

            modelBuilder.Entity("Domain.Entities.ShoeModel", b =>
                {
                    b.HasOne("Domain.Entities.Brand", null)
                        .WithMany("ShoeModels")
                        .HasForeignKey("BrandId");

                    b.HasOne("Domain.Entities.Report", null)
                        .WithMany("MissingShoeModels")
                        .HasForeignKey("ReportId");

                    b.HasOne("Domain.Entities.Report", null)
                        .WithMany("ParkingShoeModels")
                        .HasForeignKey("ReportId1");

                    b.HasOne("Domain.Entities.Report", null)
                        .WithMany("StoreShoeModels")
                        .HasForeignKey("ReportId2");

                    b.HasOne("Domain.Entities.Report", null)
                        .WithMany("SurplusShoeModels")
                        .HasForeignKey("ReportId3");

                    b.HasOne("Domain.Entities.Report", null)
                        .WithMany("TotalShoeModels")
                        .HasForeignKey("ReportId4");
                });

            modelBuilder.Entity("Domain.Entities.Brand", b =>
                {
                    b.Navigation("ShoeModels");
                });

            modelBuilder.Entity("Domain.Entities.Report", b =>
                {
                    b.Navigation("MissingShoeModels");

                    b.Navigation("ParkingShoeModels");

                    b.Navigation("StoreShoeModels");

                    b.Navigation("SurplusShoeModels");

                    b.Navigation("TotalShoeModels");
                });

            modelBuilder.Entity("Domain.Entities.ShoeModel", b =>
                {
                    b.Navigation("Sizes");
                });
#pragma warning restore 612, 618
        }
    }
}
