// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProyectoManhattan.Infrastructure.Persistance;

#nullable disable

namespace ProyectoManhattan.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240925141505_BrandReportInfoConvertedToEntity2")]
    partial class BrandReportInfoConvertedToEntity2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Brand", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("SapName")
                        .HasColumnType("text");

                    b.Property<string>("Uneco")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("Domain.Entities.BrandReportInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandParkingStockId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReportId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrandParkingStockId");

                    b.HasIndex("ReportId");

                    b.ToTable("BrandReportInfo");
                });

            modelBuilder.Entity("Domain.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CalculationTime")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Domain.Entities.Shoe", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("BrandSapName")
                        .HasColumnType("text");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Ean")
                        .HasColumnType("text");

                    b.Property<string>("Matnr")
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<int?>("ShoeModelId")
                        .HasColumnType("integer");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShoeModelId");

                    b.ToTable("Shoe");
                });

            modelBuilder.Entity("Domain.Entities.ShoeModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("integer");

                    b.Property<int?>("BrandReportInfoId")
                        .HasColumnType("integer");

                    b.Property<int?>("BrandReportInfoId1")
                        .HasColumnType("integer");

                    b.Property<int?>("BrandReportInfoId2")
                        .HasColumnType("integer");

                    b.Property<string>("BrandSapName")
                        .HasColumnType("text");

                    b.Property<string>("Family")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("RefWithOutSize")
                        .HasColumnType("text");

                    b.Property<string>("Uneco")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("BrandReportInfoId");

                    b.HasIndex("BrandReportInfoId1");

                    b.HasIndex("BrandReportInfoId2");

                    b.ToTable("ShoeModel");
                });

            modelBuilder.Entity("Domain.Entities.BrandReportInfo", b =>
                {
                    b.HasOne("Domain.Entities.Brand", "BrandParkingStock")
                        .WithMany()
                        .HasForeignKey("BrandParkingStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Report", null)
                        .WithMany("BrandReportInfos")
                        .HasForeignKey("ReportId");

                    b.Navigation("BrandParkingStock");
                });

            modelBuilder.Entity("Domain.Entities.Shoe", b =>
                {
                    b.HasOne("Domain.Entities.ShoeModel", null)
                        .WithMany("Sizes")
                        .HasForeignKey("ShoeModelId");
                });

            modelBuilder.Entity("Domain.Entities.ShoeModel", b =>
                {
                    b.HasOne("Domain.Entities.Brand", null)
                        .WithMany("ShoeModels")
                        .HasForeignKey("BrandId");

                    b.HasOne("Domain.Entities.BrandReportInfo", null)
                        .WithMany("MissingShoeModels")
                        .HasForeignKey("BrandReportInfoId");

                    b.HasOne("Domain.Entities.BrandReportInfo", null)
                        .WithMany("SurplusShoeModels")
                        .HasForeignKey("BrandReportInfoId1");

                    b.HasOne("Domain.Entities.BrandReportInfo", null)
                        .WithMany("TotalShoeModels")
                        .HasForeignKey("BrandReportInfoId2");
                });

            modelBuilder.Entity("Domain.Entities.Brand", b =>
                {
                    b.Navigation("ShoeModels");
                });

            modelBuilder.Entity("Domain.Entities.BrandReportInfo", b =>
                {
                    b.Navigation("MissingShoeModels");

                    b.Navigation("SurplusShoeModels");

                    b.Navigation("TotalShoeModels");
                });

            modelBuilder.Entity("Domain.Entities.Report", b =>
                {
                    b.Navigation("BrandReportInfos");
                });

            modelBuilder.Entity("Domain.Entities.ShoeModel", b =>
                {
                    b.Navigation("Sizes");
                });
#pragma warning restore 612, 618
        }
    }
}
